<?php

namespace Tests\Feature;

use App\Models\Account;
use App\Models\Person;
use App\Models\Product;
use App\Models\Supplier;
use App\Models\Unit;
use App\Models\User;
use App\Services\BalanceService;
use App\Services\InventoryService;
use App\Services\ReportExportService;
use Illuminate\Foundation\Http\Middleware\ValidateCsrfToken;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Testing\TestResponse;
use PhpOffice\PhpSpreadsheet\IOFactory;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use Tests\TestCase;

/**
 * Verifies the Excel export system end to end over real HTTP responses
 * (not just the underlying data service): every endpoint must return a
 * genuine ZIP-based Office Open XML workbook - starting with the "PK"
 * local-file-header magic bytes, with the correct spreadsheet
 * Content-Type and a correct Content-Disposition filename - for
 * authenticated requests only, whether filtered or not, and even when
 * the filtered result is empty. For the two tests that matter most
 * (an unfiltered export and a customer statement), the generated bytes
 * are parsed back with PhpSpreadsheet and real cell values are asserted,
 * not just that *something* downloaded.
 */
class ReportExcelExportTest extends TestCase
{
    use RefreshDatabase;

    private ReportExportService $reports;

    private BalanceService $balances;

    private Product $rice;

    private Account $cash;

    protected function setUp(): void
    {
        parent::setUp();
        $this->withoutMiddleware(ValidateCsrfToken::class);
        $this->actingAs(User::factory()->create());
        $this->reports = app(ReportExportService::class);
        $this->balances = app(BalanceService::class);

        $bag = Unit::create(['name' => 'Bag', 'abbreviation' => 'bag']);
        $this->rice = Product::create([
            'base_unit_id' => $bag->id,
            'name' => 'Excel Export Rice',
            'sku' => 'XL-RICE',
            'default_cost_price' => 10,
            'default_selling_price' => 25,
            'is_active' => true,
        ]);
        app(InventoryService::class)->record($this->rice, 1000, null, 'purchase', 'purchase', null, null, 'Opening stock', null, 'in', 10);

        $this->cash = Account::create([
            'name' => 'Excel Export Cash',
            'type' => 'cash',
            'opening_balance' => 0,
            'currency' => 'USD',
            'is_active' => true,
        ]);
    }

    /**
     * Excel::download() returns a Symfony BinaryFileResponse, which streams
     * the workbook straight from a temp file at send() time rather than
     * holding the bytes in the Response object - so getContent() is empty
     * and the real bytes have to be read from the underlying file instead.
     */
    private function xlsxBytes(TestResponse $response): string
    {
        $file = $response->baseResponse->getFile();

        return file_get_contents($file->getPathname());
    }

    private function assertIsRealXlsxResponse(TestResponse $response): void
    {
        $response->assertOk();
        $contentType = $response->headers->get('content-type');
        $this->assertNotNull($contentType);
        $this->assertStringContainsString('spreadsheetml', $contentType);
        $this->assertStringStartsWith('PK', $this->xlsxBytes($response), 'Response body must be a real ZIP-based .xlsx file, not HTML/JSON/CSV.');
    }

    private function loadSpreadsheet(TestResponse $response): Spreadsheet
    {
        $path = tempnam(sys_get_temp_dir(), 'xlsx_test_').'.xlsx';
        file_put_contents($path, $this->xlsxBytes($response));
        $spreadsheet = IOFactory::load($path);
        unlink($path);

        return $spreadsheet;
    }

    // --- 1. Transaction Excel export (+ real workbook inspection) ---

    public function test_transactions_excel_endpoint_returns_a_real_inspectable_workbook(): void
    {
        $ali = Person::create(['name' => 'Ali Hassan', 'is_active' => true, 'is_customer' => true, 'roles' => ['customer']]);
        $this->postJson('/api/sales', [
            'customer_id' => $ali->id,
            'amount_paid' => 0,
            'items' => [['product_id' => $this->rice->id, 'quantity' => 4, 'unit_price' => 25]],
        ])->assertCreated();

        $response = $this->get('/api/reports/transactions/excel');

        $this->assertIsRealXlsxResponse($response);
        $this->assertStringContainsString('attachment; filename=transactions-report-', $response->headers->get('content-disposition'));

        $sheet = $this->loadSpreadsheet($response)->getActiveSheet();
        $this->assertSame('GEDI FINANCE', $sheet->getCell('A1')->getValue());
        $this->assertSame('BUSINESS TRANSACTION REPORT', $sheet->getCell('A4')->getValue());
    }

    // --- 2. Sales Excel export ---

    public function test_sales_excel_endpoint_returns_a_real_workbook(): void
    {
        $response = $this->get('/api/reports/sales/excel');

        $this->assertIsRealXlsxResponse($response);
        $this->assertStringContainsString('attachment; filename=sales-report-', $response->headers->get('content-disposition'));
    }

    // --- 3. Purchase Excel export ---

    public function test_purchases_excel_endpoint_returns_a_real_workbook(): void
    {
        $response = $this->get('/api/reports/purchases/excel');

        $this->assertIsRealXlsxResponse($response);
        $this->assertStringContainsString('attachment; filename=purchases-report-', $response->headers->get('content-disposition'));
    }

    // --- 4. Customer statement Excel (+ real workbook inspection + Debit/Credit/Balance columns) ---

    public function test_customer_statement_excel_contains_correct_debit_credit_running_balance(): void
    {
        $ali = Person::create(['name' => 'Ali Hassan', 'is_active' => true, 'is_customer' => true, 'roles' => ['customer']]);

        $this->postJson('/api/sales', [
            'customer_id' => $ali->id,
            'amount_paid' => 0,
            'items' => [['product_id' => $this->rice->id, 'quantity' => 12, 'unit_price' => 25]],
        ])->assertCreated(); // 300 owed
        $this->postJson("/api/people/{$ali->id}/payments", [
            'amount' => 100,
            'account_id' => $this->cash->id,
        ])->assertOk();

        $response = $this->get("/api/reports/transactions/excel?person_id={$ali->id}");
        $this->assertIsRealXlsxResponse($response);
        $this->assertStringContainsString('attachment; filename=customer-statement-ali-hassan', $response->headers->get('content-disposition'));

        $spreadsheet = $this->loadSpreadsheet($response);
        $this->assertSame('Ali Hassan', $spreadsheet->getSheetNames()[0]);

        $sheet = $spreadsheet->getActiveSheet();
        $this->assertSame('CUSTOMER STATEMENT', $sheet->getCell('A4')->getValue());
        $this->assertSame('Customer: Ali Hassan', $sheet->getCell('A5')->getValue());

        // Header row is row 10: Date | Reference | Type | Description | Debit | Credit | Balance
        $this->assertSame('Debit', $sheet->getCell('E10')->getValue());
        $this->assertSame('Credit', $sheet->getCell('F10')->getValue());
        $this->assertSame('Balance', $sheet->getCell('G10')->getValue());

        // Row 11: the 300 credit sale - a debit, running balance 300.
        $this->assertSame(300.0, $sheet->getCell('E11')->getValue());
        $this->assertSame('', (string) $sheet->getCell('F11')->getValue());
        $this->assertSame(300.0, $sheet->getCell('G11')->getValue());

        // Row 12: the 100 payment - a credit, running balance 200.
        $this->assertSame('', (string) $sheet->getCell('E12')->getValue());
        $this->assertSame(100.0, $sheet->getCell('F12')->getValue());
        $this->assertSame(200.0, $sheet->getCell('G12')->getValue());

        // The final running balance must equal the real BalanceService figure.
        $this->assertSame('200.00', $this->balances->customerReceivableBalance($ali->fresh()));
    }

    // --- 5. Supplier statement Excel ---

    public function test_supplier_statement_excel_returns_a_real_workbook_scoped_to_that_supplier(): void
    {
        $supplierA = Supplier::create(['supplier_code' => 'XL-SUP-A', 'name' => 'Supplier A', 'is_active' => true]);
        $supplierB = Supplier::create(['supplier_code' => 'XL-SUP-B', 'name' => 'Supplier B', 'is_active' => true]);

        $this->postJson('/api/purchases', [
            'supplier_id' => $supplierA->id,
            'amount_paid' => 0,
            'items' => [['product_id' => $this->rice->id, 'quantity' => 40, 'unit_cost' => 10]],
        ])->assertCreated(); // 400 payable

        $this->postJson('/api/purchases', [
            'supplier_id' => $supplierB->id,
            'amount_paid' => 0,
            'items' => [['product_id' => $this->rice->id, 'quantity' => 10, 'unit_cost' => 10]],
        ])->assertCreated();

        $response = $this->get("/api/reports/purchases/excel?supplier_id={$supplierA->id}");
        $this->assertIsRealXlsxResponse($response);
        $this->assertStringContainsString('attachment; filename=supplier-statement-supplier-a', $response->headers->get('content-disposition'));

        $report = $this->reports->purchasesReport(['supplier_id' => (string) $supplierA->id]);
        $this->assertSame('SUPPLIER STATEMENT', $report['title']);
        $this->assertSame(1, $report['count']);
        $this->assertSame(
            $this->balances->supplierBalance($supplierA->fresh()),
            $report['totals']['Outstanding Balance'],
        );
        $this->assertSame('400.00', $report['totals']['Outstanding Balance']);
    }

    // --- 6 & 7. Authentication ---

    public function test_excel_endpoints_require_authentication(): void
    {
        auth()->logout();

        $this->getJson('/api/reports/transactions/excel')->assertUnauthorized();
        $this->getJson('/api/reports/sales/excel')->assertUnauthorized();
        $this->getJson('/api/reports/purchases/excel')->assertUnauthorized();
    }

    // --- 8. Filters are respected ---

    public function test_filtered_excel_reflects_only_the_filtered_rows_not_the_whole_database(): void
    {
        $ali = Person::create(['name' => 'Ali Hassan', 'is_active' => true, 'is_customer' => true, 'roles' => ['customer']]);
        $bilal = Person::create(['name' => 'Bilal', 'is_active' => true, 'is_customer' => true, 'roles' => ['customer']]);

        $this->postJson('/api/sales', [
            'customer_id' => $ali->id,
            'amount_paid' => 0,
            'items' => [['product_id' => $this->rice->id, 'quantity' => 4, 'unit_price' => 25]],
        ])->assertCreated();
        $this->postJson('/api/sales', [
            'customer_id' => $bilal->id,
            'amount_paid' => 0,
            'items' => [['product_id' => $this->rice->id, 'quantity' => 4, 'unit_price' => 25]],
        ])->assertCreated();

        $unfiltered = $this->reports->transactionsReport([]);
        $this->assertSame(2, $unfiltered['count']);

        $filtered = $this->reports->transactionsReport(['person_id' => (string) $ali->id]);
        $this->assertSame(1, $filtered['count']);

        $response = $this->get("/api/reports/transactions/excel?person_id={$ali->id}");
        $this->assertIsRealXlsxResponse($response);
    }

    // --- 9. Customer filtering does not leak another customer's records ---

    public function test_customer_statement_never_leaks_another_customers_transactions(): void
    {
        $ali = Person::create(['name' => 'Ali Hassan', 'is_active' => true, 'is_customer' => true, 'roles' => ['customer']]);
        $bilal = Person::create(['name' => 'Bilal', 'is_active' => true, 'is_customer' => true, 'roles' => ['customer']]);

        $this->postJson('/api/sales', [
            'customer_id' => $ali->id,
            'amount_paid' => 0,
            'items' => [['product_id' => $this->rice->id, 'quantity' => 4, 'unit_price' => 25]],
        ])->assertCreated();
        $this->postJson('/api/sales', [
            'customer_id' => $bilal->id,
            'amount_paid' => 0,
            'items' => [['product_id' => $this->rice->id, 'quantity' => 8, 'unit_price' => 25]],
        ])->assertCreated();

        $report = $this->reports->transactionsReport(['person_id' => (string) $ali->id]);
        $this->assertSame(1, $report['count']);
        foreach ($report['rows'] as $row) {
            $this->assertStringNotContainsString('Bilal', json_encode($row));
        }
    }

    // --- 10. Supplier filtering does not leak another supplier's records ---

    public function test_supplier_statement_never_leaks_another_suppliers_purchases(): void
    {
        $supplierA = Supplier::create(['supplier_code' => 'XL-LEAK-A', 'name' => 'Leak Supplier A', 'is_active' => true]);
        $supplierB = Supplier::create(['supplier_code' => 'XL-LEAK-B', 'name' => 'Leak Supplier B', 'is_active' => true]);

        $this->postJson('/api/purchases', [
            'supplier_id' => $supplierA->id,
            'amount_paid' => 0,
            'items' => [['product_id' => $this->rice->id, 'quantity' => 10, 'unit_cost' => 10]],
        ])->assertCreated();
        $this->postJson('/api/purchases', [
            'supplier_id' => $supplierB->id,
            'amount_paid' => 0,
            'items' => [['product_id' => $this->rice->id, 'quantity' => 20, 'unit_cost' => 10]],
        ])->assertCreated();

        $report = $this->reports->purchasesReport(['supplier_id' => (string) $supplierA->id]);
        $this->assertSame(1, $report['count']);
        foreach ($report['rows'] as $row) {
            $this->assertStringNotContainsString('Leak Supplier B', json_encode($row));
        }
    }

    // --- 11. Empty result export ---

    public function test_a_filter_matching_nothing_still_produces_a_valid_workbook(): void
    {
        $noHistory = Person::create(['name' => 'No History Customer', 'is_active' => true, 'is_customer' => true, 'roles' => ['customer']]);

        $response = $this->get("/api/reports/transactions/excel?person_id={$noHistory->id}");

        $this->assertIsRealXlsxResponse($response);

        $report = $this->reports->transactionsReport(['person_id' => (string) $noHistory->id]);
        $this->assertSame(0, $report['count']);
        $this->assertSame([], $report['rows']);
    }

    // --- 12 & 13. Filename and Content-Type already asserted per-endpoint above; one more explicit check: ---

    public function test_excel_filenames_are_descriptive_and_dated(): void
    {
        $today = now()->format('Y-m-d');

        $transactions = $this->get('/api/reports/transactions/excel');
        $this->assertSame("attachment; filename=transactions-report-{$today}.xlsx", $transactions->headers->get('content-disposition'));

        $sales = $this->get('/api/reports/sales/excel');
        $this->assertSame("attachment; filename=sales-report-{$today}.xlsx", $sales->headers->get('content-disposition'));

        $purchases = $this->get('/api/reports/purchases/excel');
        $this->assertSame("attachment; filename=purchases-report-{$today}.xlsx", $purchases->headers->get('content-disposition'));
    }

    // --- 14. Response is a real XLSX file - already asserted by assertIsRealXlsxResponse() in every test above ---

    public function test_report_titles_switch_correctly_between_general_and_person_specific(): void
    {
        $ali = Person::create(['name' => 'Ali Hassan', 'is_active' => true, 'is_customer' => true, 'roles' => ['customer']]);
        $supplier = Supplier::create(['supplier_code' => 'XL-TITLE-SUP', 'name' => 'Title Supplier', 'is_active' => true]);

        $this->assertSame('BUSINESS TRANSACTION REPORT', $this->reports->transactionsReport([])['title']);
        $this->assertSame('CUSTOMER STATEMENT', $this->reports->transactionsReport(['person_id' => (string) $ali->id])['title']);
        $this->assertSame('SALES REPORT', $this->reports->salesReport([])['title']);
        $this->assertSame('CUSTOMER STATEMENT', $this->reports->salesReport(['customer_id' => (string) $ali->id])['title']);
        $this->assertSame('PURCHASE REPORT', $this->reports->purchasesReport([])['title']);
        $this->assertSame('SUPPLIER STATEMENT', $this->reports->purchasesReport(['supplier_id' => (string) $supplier->id])['title']);
    }

    public function test_a_voided_sale_is_excluded_from_the_sales_export_data(): void
    {
        $ali = Person::create(['name' => 'Ali Hassan', 'is_active' => true, 'is_customer' => true, 'roles' => ['customer']]);
        $sale = $this->postJson('/api/sales', [
            'customer_id' => $ali->id,
            'amount_paid' => 0,
            'items' => [['product_id' => $this->rice->id, 'quantity' => 4, 'unit_price' => 25]],
        ])->assertCreated()->json('sale');

        $this->postJson("/api/sales/{$sale['id']}/void", [])->assertOk();

        $report = $this->reports->salesReport([]);
        $this->assertSame(0, $report['count'], 'A voided sale must not appear in the active Sales Report export.');
    }

    public function test_excel_export_rejects_an_id_for_a_person_that_does_not_exist(): void
    {
        $response = $this->getJson('/api/reports/transactions/excel?person_id=999999');
        $response->assertStatus(422);
    }
}
